update dockerfile, docker-compose, workflows

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -1,19 +1,33 @@
-name: Local CI/CD
+name: Docker Compose CI
 
 on:
   push:
     branches: [ "main" ]
-  workflow_dispatch:
+  pull_request:
+    branches: [ "main" ]
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      - name: Checkout source code
+        uses: actions/checkout@v4
 
-    - name: Build Docker Image
-      run: docker-compose build
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
-    - name: Run App with Docker Compose
-      run: docker-compose up -d
+      - name: Install Docker Compose
+        run: |
+          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
+          sudo chmod +x /usr/local/bin/docker-compose
+
+      - name: Build and run all services
+        run: docker-compose up -d --build
+
+      - name: Wait for Sanic to start
+        run: sleep 10
+
+      - name: Check Sanic is responding
+        run: |
+          curl --fail http://localhost:8080 || (echo "Sanic failed to start" && exit 1)
